name: EatingPeace
favicon: null
layout_spectrum: 0.7386212593410164
typography_spectrum: 0.9084481906611472
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.26282253256067634
  lightness: 0.7153449410106987
  saturation: 0.3354944388847798
  rhythmicContrast: 0.4206823296844959
purpose: []
