name: EatingPeace
favicon: null
layout_spectrum: 0.7386212593410164
typography_spectrum: 0.9084481906611472
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff0066'
    - '#d02469'
    - '#f0b3d7'
    - '#ed6fa2'
  brandStrength: 0.4375
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
