typography_spectrum: 0.9084481906611472
color:
  brandColors:
    - '#ffffff'
    - '#ff0066'
    - '#d02469'
    - '#f0b3d7'
    - '#ed6fa2'
  brandStrength: 0.4375
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Grace Bell
  email: grace@workwithgrace.com
  url: workwithgrace.com
name: EatingPeace
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 'Question your thinking, dissolve suffering'
    url: 'http://workwithgrace.com/'
    type: external
favicon: null
title: >-
  Ending Compulsion, Dependency, Addiction with Mindful Self-Inquiry & The Work
  of Byron Katie
description: 'Grace Bell, Facilitator of The Work and Founder of Work With Grace'
purpose: []
